### 1.`Create a 1D NumPy array with values from 0 to 9

In [2]:
import numpy as np

In [3]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2.Create a 3x3 NumPy array of all zeros.

In [5]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### 3.Create a 5x5 identity matrix

In [8]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### 4.Create a NumPy array of 10 random integers between 1 and 100.

In [10]:
random_array=np.random.randint(1,100,10)
random_array

array([59, 25, 44, 46, 41, 14, 54, 47, 14, 85], dtype=int32)

 ### 5.Generate a 2D array (3x3) with random floats between 0 and 1.

In [12]:
arr=np.random.random((3,3))
arr

array([[0.23959199, 0.71055892, 0.65817667],
       [0.05237468, 0.83724634, 0.16578378],
       [0.58484883, 0.64997213, 0.99472603]])

### 6.Replace all odd numbers in a NumPy array with -1

In [13]:
hi=np.array([1,3,5,7,8,9,10])
hi

array([ 1,  3,  5,  7,  8,  9, 10])

In [20]:
hi= np.where(hi%2!=0,-1,hi)
hi

array([-1, -1, -1, -1,  8, -1, 10])

### 7.Reverse a 1D NumPy array (e.g., [1, 2, 3] becomes [3, 2, 1]).

In [21]:
a=np.array([3,4,5,6,7,8,9])
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

### 8. Stack two 1D arrays vertically and horizontally

In [27]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [28]:
a

array([1, 2, 3])

In [29]:
b

array([4, 5, 6])

In [31]:
c=np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
d=np.hstack((a,b))
d

array([1, 2, 3, 4, 5, 6])

### 9.Create a 3x3 matrix and compute its mean, median, and standard deviation

In [37]:
a=np.random.randint(1,100,size=(3,3))
a

array([[62, 97, 68],
       [97, 23, 16],
       [38, 77,  4]], dtype=int32)

In [38]:
np.mean(a)

np.float64(53.55555555555556)

In [39]:
np.mean(a,axis=0) #column mean

array([65.66666667, 65.66666667, 29.33333333])

In [40]:
np.median(a) #(n+1)/2  #first sorts in ascending order.

np.float64(62.0)

In [41]:
a

array([[62, 97, 68],
       [97, 23, 16],
       [38, 77,  4]], dtype=int32)

In [42]:
np.median(a,axis=1)

array([68., 23., 38.])

In [43]:
np.std(a)

np.float64(32.73839441902737)

### 10. Extract all elements from an array greater than a given value.

In [45]:
arr=np.random.randint(1,100,10)
arr

array([49, 30, 30, 18, 50, 92, 77, 74,  8,  8], dtype=int32)

In [46]:
arr[arr>50]

array([92, 77, 74], dtype=int32)

### 11. Find the indices of non-zero elements in a NumPy array.


In [48]:
arr=np.array([1,0,2,3,4,0,0,0])
arr


array([1, 0, 2, 3, 4, 0, 0, 0])

In [49]:
np.nonzero(arr) #shows index position

(array([0, 2, 3, 4]),)

### 12.Create a 10-element array and sort it

In [51]:
arr=np.random.randint(1,200,10)
arr

array([152,  80,   8,  73,  49,  30,  41, 176,  91, 110], dtype=int32)

In [53]:
np.sort(arr)

array([  8,  30,  41,  49,  73,  80,  91, 110, 152, 176], dtype=int32)

In [55]:
arr=np.sort(arr)
arr

array([  8,  30,  41,  49,  73,  80,  91, 110, 152, 176], dtype=int32)

### 13.Check if two NumPy arrays are equal

In [57]:
arr1=([1,2,3,4])
arr2=([1,2,3,4])
hi=np.array_equal(arr1,arr2)
hi

True

### 14.Create a 4x4 matrix and calculate the sum of each column.

In [61]:
arr1=np.random.randint(1,50,size=(4,4))
arr1

array([[23,  5, 11,  7],
       [37, 32, 27, 27],
       [30, 45,  9, 47],
       [12, 36,  4, 19]], dtype=int32)

In [63]:
np.sum(arr1,axis=0)

array([102, 118,  51, 100])