# Numpy(numerical python)
**Numpy is a python library used for numerical and scientific computing.**

In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
lst=[10,20,30,40,50]
print(lst)
print(type(lst))

[10, 20, 30, 40, 50]
<class 'list'>


## **convert list into array( different attributes in numpy array (shape , size , dimension )**
#### 1 dimensional array

In [3]:
arr=np.array(lst)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
arr

array([10, 20, 30, 40, 50])

In [5]:
arr.ndim   #array.ndim gives dimension of array

1

In [6]:
arr.size #gives total no of elements present in array.

5

In [7]:
arr.shape #array shape of 5 in a 1 direction.

(5,)

 #### 2 dimensional array

In [8]:
lst2=[[2,4,5,6],[2,7,3,4],[50,6,8,7]]
lst2[0]


[2, 4, 5, 6]

In [9]:
arr2d=np.array(lst2)
arr2d

array([[ 2,  4,  5,  6],
       [ 2,  7,  3,  4],
       [50,  6,  8,  7]])

In [11]:
arr2d.ndim  #note:list is heterogeneous and array is homogeneous.

2

In [12]:
arr2d.shape

(3, 4)

In [13]:
arr2d.size

12

#### 3 dimensional array

In [19]:
lst1=[[1,2,3],[4,5,6],[5,6,7]]
lst2=[[8,9,10],[1,2,4],[4,8,9]]
lst3=[lst1,lst2]
lst3
lst3[0]

[[1, 2, 3], [4, 5, 6], [5, 6, 7]]

In [21]:
arr3d=np.array(lst3)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  7]],

       [[ 8,  9, 10],
        [ 1,  2,  4],
        [ 4,  8,  9]]])

In [22]:
arr3d.ndim

3

In [23]:
arr3d.shape  #here in output 2 is two dimesional type, and 3 ,3 is rows and columns)

(2, 3, 3)

In [24]:
arr3d.size

18

## **data types**
#### float into integer

In [25]:
data=[10.3,10.33,30.888,9.7]
np.array(data)

array([10.3  , 10.33 , 30.888,  9.7  ])

In [26]:
np.array(data,dtype=int) #by default its always in floating point value.and we convert into int like this.

array([10, 10, 30,  9])

## integer into float

In [27]:

hi=[1,2,3,4,5]
np.array(hi,dtype=float)

array([1., 2., 3., 4., 5.])

## boolean(true or false):everything except 0 is true.eg:-100,-1,2 etc.

In [28]:
lst=[10,0,-29,70]
np.array(lst,dtype=bool)

array([ True, False,  True,  True])