In [1]:
import numpy as np

## random number generation for 1d, 2d, 3d, special function(zeros,ones,identity)
### 0 to 1 range

In [40]:
arr=np.random.random(5)
arr   #by default output is given in float #range in o and 1

array([0.80650702, 0.30847803, 0.20106705, 0.53347035, 0.88028022])

In [3]:
np.random.random((2,3))


array([[0.60256974, 0.19081157, 0.71481939],
       [0.98452449, 0.77822087, 0.39777894]])

In [41]:
np.random.random((3,3,4))

array([[[0.00184451, 0.76322755, 0.93179539, 0.65940019],
        [0.45204262, 0.23501631, 0.46232877, 0.94217659],
        [0.45515114, 0.01742376, 0.96040868, 0.8692236 ]],

       [[0.13784819, 0.93107929, 0.74831206, 0.48351903],
        [0.75612418, 0.12778197, 0.37634444, 0.09066443],
        [0.3700837 , 0.10359275, 0.22924737, 0.33506656]],

       [[0.02001835, 0.7692637 , 0.23691915, 0.24260008],
        [0.1474485 , 0.18582437, 0.76986162, 0.41352936],
        [0.75446675, 0.16667483, 0.28639743, 0.69462693]]])

In [46]:
np.random.random((2,3,4))*40

array([[[ 8.98789389, 10.21144588,  3.62138817, 15.15142035],
        [14.55607486, 26.31045142, 34.14475472, 11.35449527],
        [ 8.066058  , 24.75639037, 25.43722253, 14.40712612]],

       [[26.54465725, 12.63665074, 33.30580693, 27.35330714],
        [19.00961919, 33.85296854, 20.34888899, 32.32930344],
        [15.32675603, 27.22423914,  9.85735346, 10.44686239]]])

### now if we want to give range ourselves.

#### 50 to 80

In [49]:
np.random.randint(5,800,5) #50 and 80 is range and 10 is 10 random values gives. this is for 1 dimension

array([750, 391,  55,  66, 133], dtype=int32)

In [7]:
np.random.randint(50,80, size=(4,3))  #this is two dimension.

array([[77, 57, 58],
       [72, 55, 74],
       [76, 58, 51],
       [65, 62, 62]], dtype=int32)

In [50]:
np.random.randint(90,100, size=(2,3,3)) #this is three dimension.

array([[[91, 99, 97],
        [92, 98, 97],
        [92, 94, 90]],

       [[97, 91, 95],
        [90, 92, 92],
        [92, 93, 94]]], dtype=int32)


## special function in numpy(zeros, ones, identity)
#### zeros

In [9]:
np.zeros(10,dtype=int) #gives 10 zeros number

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.zeros((4,3),dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [12]:
np.zeros((3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [13]:
np.zeros((2,2),dtype=bool)

array([[False, False],
       [False, False]])

  #### ones

In [14]:
np.ones((2,2),dtype=bool)

array([[ True,  True],
       [ True,  True]])

 #### identity

In [15]:
np.identity(2,dtype=bool)

array([[ True, False],
       [False,  True]])

In [52]:
np.identity((5),dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### different arithmetic operators

In [55]:
arr1=np.random.randint(40,60,size=(2,2))
arr2=np.random.randint(40,60,size=(2,2))
arr1 

array([[58, 52],
       [42, 56]], dtype=int32)

In [56]:
arr2

array([[42, 48],
       [53, 53]], dtype=int32)

In [57]:
arr1+arr2 #addition

array([[100, 100],
       [ 95, 109]], dtype=int32)

In [20]:
arr1-arr2

array([[ 4, -6],
       [ 2,  0]], dtype=int32)

In [21]:
arr1*arr2

array([[2021, 2592],
       [1763, 2809]], dtype=int32)

## real examples practise
### convert degree celcius into feranite.

In [22]:
temp_in_degree=np.array([10,20,0,0,0,0])
#degree to F formula:0°C × 9/5) + 32 = 32°F
temp_in_f=temp_in_degree*(9/5)+32
temp_in_f

array([50., 68., 32., 32., 32., 32.])

#### increase the salaey of every employee by 10%

In [23]:
salary=np.array([10000,20000,30000])
salary

array([10000, 20000, 30000])

In [24]:
salary_after_increase=salary*1.1
salary_after_increase

array([11000., 22000., 33000.])

#### discount the price of every item by20%

In [25]:
sales_data=np.array([10000,20000,30000])
sales_after_discount=sales_data*0.8
sales_after_discount

array([ 8000., 16000., 24000.])

### Different array Operations

#### scalar operations

In [26]:
#adding constant value
arr=np.array(55)
arr

array(55)

In [27]:
arr+10

np.int64(65)

In [28]:
arr-20

np.int64(35)

#### vector operations

In [29]:
arr1=np.array([22,80]) 
arr1

array([22, 80])

In [30]:
arr2=np.array([1,3])
arr3=arr1+arr2
arr3

array([23, 83])

### Indexing and slicing


In [58]:
arr1=np.random.randint(1,100,10)
arr1

array([86, 69, 78, 72, 73, 83, 73,  6, 49, 64], dtype=int32)

In [59]:
arr1[-1] #indexing

np.int32(64)

In [33]:
arr1[0:10:2]  #slicing

array([23, 88, 63, 51, 37], dtype=int32)

In [34]:
arr1[-3::]

array([92, 37, 31], dtype=int32)

In [60]:
arr1[-1:6:-1]

array([64, 49,  6], dtype=int32)