In [1]:
import numpy as np

In [2]:
arr2d=np.random.randint(1,100, size=(3,4))
arr2d

array([[30, 19, 43, 20],
       [74, 33, 20, 39],
       [73, 45, 27, 54]], dtype=int32)

## Different aggregate functions=min,max,mean,median,std var,cumsum,sun,argmin,argmax)

### min

In [3]:
np.min(arr2d)

np.int32(19)

In [4]:
np.min(arr2d,axis=0) #fetch minimum value from the column using axis=0

array([30, 19, 20, 20], dtype=int32)

In [5]:
arr2d

array([[30, 19, 43, 20],
       [74, 33, 20, 39],
       [73, 45, 27, 54]], dtype=int32)

In [6]:
np.min(arr2d,axis=1) #fetch minimum value row wise.

array([19, 20, 27], dtype=int32)

### max

In [7]:
arr2d

array([[30, 19, 43, 20],
       [74, 33, 20, 39],
       [73, 45, 27, 54]], dtype=int32)

In [8]:
np.max(arr2d)

np.int32(74)

In [9]:
np.max(arr2d, axis=0)

array([74, 45, 43, 54], dtype=int32)

In [10]:
np.max(arr2d,axis=1)

array([43, 74, 73], dtype=int32)

### mean(average)

In [11]:
hi=[1,2,3,5,8,10]
mean=sum(hi)/len(hi)
mean

4.833333333333333

In [12]:
np.mean(hi) #we can directly get the mean(average) in this way.

np.float64(4.833333333333333)

In [13]:
np.mean(arr2d[1])
#mean from rows.

np.float64(41.5)

In [14]:
arr2d[1] #gives the mean of first row

array([74, 33, 20, 39], dtype=int32)

In [15]:
np.mean(arr2d[0])

np.float64(28.0)

In [16]:
arr2d[2]

array([73, 45, 27, 54], dtype=int32)

In [17]:
np.mean(arr2d, axis=1) #every row neab calculates.

array([28.  , 41.5 , 49.75])

In [18]:
np.mean(arr2d[0][1])

np.float64(19.0)

### custom average

In [19]:
sum(arr2d)

array([177,  97,  90, 113], dtype=int32)

In [20]:
arr2d.size

12

In [21]:
np.mean(arr2d,axis=0)

array([59.        , 32.33333333, 30.        , 37.66666667])

In [22]:
np.mean(arr2d,axis=1)

array([28.  , 41.5 , 49.75])

### cumulative sum

In [23]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [24]:
### Find the day the subscriber cross the 200.
np.cumsum(arr) # sum gardai janxa.

array([ 10,  30,  60, 100, 150])

In [25]:
np.cumsum(arr2d,axis=0)

array([[ 30,  19,  43,  20],
       [104,  52,  63,  59],
       [177,  97,  90, 113]])

### argmax and argmin

In [26]:
np.argmin(arr2d) #represent index position

np.int64(1)

In [27]:
arr2d

array([[30, 19, 43, 20],
       [74, 33, 20, 39],
       [73, 45, 27, 54]], dtype=int32)

In [28]:
np.argmax(arr2d,axis=1)

array([2, 0, 0])

### median (n+1)\2

In [29]:
np.median(arr)

np.float64(30.0)

In [30]:
arr

array([10, 20, 30, 40, 50])

## relational operator >,<,==,<=,>=,!=

In [31]:
#used in data filtering
hi=np.random.randint(1,100,10)
hi

array([10, 61, 37, 52, 36, 25, 71, 67, 51, 30], dtype=int32)

In [32]:
### find the element greater than 50
hi>50

array([False,  True, False,  True, False, False,  True,  True,  True,
       False])

In [36]:
hi[hi>50]

array([61, 52, 71, 67, 51], dtype=int32)

In [37]:
hi<=50

array([ True, False,  True, False,  True,  True, False, False, False,
        True])

In [38]:
hi[hi<=50]

array([10, 37, 36, 25, 30], dtype=int32)

### find element except 44

In [42]:
hi[hi!=52]

array([10, 61, 37, 36, 25, 71, 67, 51, 30], dtype=int32)

### logical operator

In [44]:
not((50>60)and(20<30))

True

In [48]:
arr=np.array([3,5,10,15,20])
arr%5==0

array([False,  True,  True,  True,  True])

### find the no that are divisible by 5 and 3

In [49]:
(arr%3==0)&(arr%5==0)

array([False, False, False,  True, False])