In [1]:
import numpy as np

### Concatenate

In [2]:
arr1=np.random.randint(1,100,size=(3,3))
arr1

array([[61, 18, 50],
       [65, 44,  7],
       [10, 13, 41]], dtype=int32)

In [3]:
arr2=np.random.randint(1,100,size=(3,3))
arr2

array([[ 9, 74, 57],
       [76, 15, 60],
       [70, 88, 95]], dtype=int32)

In [4]:
merged_array = np.concatenate((arr1, arr2))
merged_array

array([[61, 18, 50],
       [65, 44,  7],
       [10, 13, 41],
       [ 9, 74, 57],
       [76, 15, 60],
       [70, 88, 95]], dtype=int32)

### Transpose

In [5]:
arr2d=np.random.randint(1,100,size=(4,3))
arr2d

array([[89, 26, 11],
       [80, 33, 79],
       [49, 58, 57],
       [75, 66, 81]], dtype=int32)

In [6]:
np.transpose(arr2d)

array([[89, 80, 49, 75],
       [26, 33, 58, 66],
       [11, 79, 57, 81]], dtype=int32)

## matrix multiplication

In [7]:
arr1=np.random.randint(1,10,size=(2,2))
arr2=np.random.randint(1,10,size=(2,2))
arr1

array([[9, 2],
       [3, 1]], dtype=int32)

In [8]:
arr2

array([[2, 5],
       [3, 4]], dtype=int32)

In [9]:
arr1*arr2

array([[18, 10],
       [ 9,  4]], dtype=int32)

In [12]:
np.dot(arr1,arr2) #matrix multiply

array([[24, 53],
       [ 9, 19]], dtype=int32)

In [17]:
arr1=np.random.randint(1,100,size=(4,5))
arr1

array([[84, 19, 95, 40, 93],
       [30, 26, 65,  9, 35],
       [73, 45, 72, 96, 67],
       [91, 52, 75, 66, 49]], dtype=int32)

In [14]:
arr2=np.random.randint(1,100,size=(5,3))
arr2

array([[39, 49, 92],
       [73, 16, 12],
       [73, 90, 80],
       [95, 25, 14],
       [51, 59, 78]], dtype=int32)

In [18]:
np.dot(arr1,arr2)

array([[20141, 19457, 23370],
       [10453, 10026, 11128],
       [23925, 17130, 19586],
       [21589, 16582, 19742]], dtype=int32)

### Different Functions in Numpy

### np.where(), if condition True,else condition(false)

In [19]:
arr1=np.array([1,20,33,4,5,6])
arr1

array([ 1, 20, 33,  4,  5,  6])

In [21]:
np.where(arr1%2==0) #shows index position

(array([1, 3, 5]),)

In [23]:
arr1=np.where(arr1%2==0)[0]
arr1

array([1, 3, 5])

In [27]:
np.where(arr1%2==0,'even','odd')

array(['odd', 'odd', 'odd'], dtype='<U4')

### Generate a random array and add the 10 for the even no.of array.

In [30]:
arr3=np.array([2,4,6,7,8,9])
arr3

array([2, 4, 6, 7, 8, 9])

In [33]:
np.where(arr3%2==0, arr3+10, arr3)

array([12, 14, 16,  7, 18,  9])

### np.sort()

In [35]:
arr1=np.random.randint(1,100,15)
arr1

array([61,  4, 80, 55, 85, 43, 74, 43,  6, 25, 17, 88, 82, 13, 63],
      dtype=int32)

In [36]:
np.sort(arr1)

array([ 4,  6, 13, 17, 25, 43, 43, 55, 61, 63, 74, 80, 82, 85, 88],
      dtype=int32)

In [37]:
arr1

array([61,  4, 80, 55, 85, 43, 74, 43,  6, 25, 17, 88, 82, 13, 63],
      dtype=int32)

In [41]:
np.sort(arr1)[::-1]

array([88, 85, 82, 80, 74, 63, 61, 55, 43, 43, 25, 17, 13,  6,  4],
      dtype=int32)

In [43]:
arr1=np.sort(arr1)[::-1]
arr1

array([88, 85, 82, 80, 74, 63, 61, 55, 43, 43, 25, 17, 13,  6,  4],
      dtype=int32)

In [44]:
arr1 #now as i reassign the data in arr1 now this decending order data has permanent data.

array([88, 85, 82, 80, 74, 63, 61, 55, 43, 43, 25, 17, 13,  6,  4],
      dtype=int32)

### np.delete()

In [45]:
np.delete(arr1,0) #0 index gets deleted.

array([85, 82, 80, 74, 63, 61, 55, 43, 43, 25, 17, 13,  6,  4],
      dtype=int32)

In [49]:
np.put(arr1,[0,1],[100,200]) #replacing
arr1

array([100, 200,  82,  80,  74,  63,  61,  55,  43,  43,  25,  17,  13,
         6,   4], dtype=int32)

### np.insert()

In [50]:
np.insert(arr1,1,1000)

array([ 100, 1000,  200,   82,   80,   74,   63,   61,   55,   43,   43,
         25,   17,   13,    6,    4], dtype=int32)

In [ ]:
#note:result dekhayena vane=temporary change if shows then permanent change ho.